# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "snowflake-blake3"
version = "0.0.0"
edition = "2021"

[dependencies.libc]
version = "~0.2.125"

[dependencies.snowflake-blake3-sys]
path = "../snowflake-blake3-sys"
