#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only

set -efuxo pipefail

################################################################################
# Build software

export CARGO_BUILD_TARGET_DIR=build

cargo build
cargo test
cargo doc

################################################################################
# Build manual

sphinxBuildFlags=(
    -a            # Disable cache (it's broken).
    -W            # Warnings as errors.
    --keep-going  # Do not stop at first warning.
)

sphinx-build "${sphinxBuildFlags[@]}" manual build/manual

################################################################################
# Check that each file contains a license identifier

script/check-license
